### ISSUE TITLE
Solway render on browsers

### ISSUE THREAD

**Issue by vv-monsalve** [vv-monsalve/Solway#4]
### OS X High Sierra Safari 11
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/67579470-28567880-f70a-11e9-93d6-fbd01189e6e5.jpg)
### Windows 10 Chrome 69
![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/48698976/67579472-28ef0f00-f70a-11e9-8959-a93412c8c346.jpg)
### Windows 10 Firefox 62
![Desktop_Windows_10_firefox_62 0_](https://user-images.githubusercontent.com/48698976/67579474-28ef0f00-f70a-11e9-8e06-d71fffca909c.jpg)

**Comment by vv-monsalve** [comment]
Windows 10 Chrome 69
![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/48698976/67579642-7a979980-f70a-11e9-9851-7290438739fa.jpg)

**Comment by m4rc1e** [comment]
Looks ok to me.

**Comment by vv-monsalve** [comment]
Ok, great, thanks
